@baseUrl = http://bookswap/api
@email= test2@test.com
@password = password

# @name auth
POST {{baseUrl}}/login HTTP/1.1	
content-type: application/json;charset=UTF-8

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###

GET {{baseUrl}}/bookshelf
Authorization: Bearer {{auth.response.body.token}}